### ISSUE TITLE
Update h1 tag colors

### ISSUE THREAD

**Issue by anfieldroadfan** [blackbriar-28/GitHub-aldo-crash-course#2]
Please update the h1 tag color ASAP:

```css
h1 {
  color: #d4901a;
}
```
